spring:
  application:
    name: api-gateway
  config:
    import: classpath:/properties/app.properties, optional:classpath:/properties/secret.properties
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:5001
          predicates:
            - Path=/auth/**, /user/**
          filters:
            - name: JwtAuthentication

        - id: order-service
          uri: http://localhost:5002
          predicates:
            - Path=/order/**
          filters:
            - name: JwtAuthentication

        - id: tracker-service
          uri: http://localhost:5003
          predicates:
            - Path=/tracker/**
          filters:
            - name: JwtAuthentication

        - id: warehouse-service
          uri: http://localhost:5004
          predicates:
            - Path=/warehouse/**
          filters:
            - name: JwtAuthentication